name: Main

on:
  push:
    branches: [ deej-main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false

      - name: "NPM Install, Build, and Cache"
        id: npm-install-build-and-cache
        uses: ./.github/actions/npm-install-build-and-cache

  publish-experimental-packages:
    name: Publish Experimental Packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Publish
        run: |
          # Set up git user for lerna to create a local commit with
          git config --global user.email "lerna-ci@mml.io"
          git config --global user.name "lerna-ci-mml"

          # Set up npm auth token from secret for publishing
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} > .npmrc

          # Publish the current commit as an "experimental" version
          version="0.0.0-experimental-$(git rev-parse --short HEAD)-$(date +'%Y%m%d')"
          echo "Publishing experimental version $version"
          ./node_modules/.bin/lerna publish $version --no-private --dist-tag experimental --ignore-scripts --ignore-changes --no-push --exact --yes


  publish-release-packages:
    name: Publish Packages
    environment: package-release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Publish
        run: |
          # Set up git user for lerna to create a local commit with
          git config --global user.email "lerna-ci@mml.io"
          git config --global user.name "lerna-ci-mml"

          # Set up npm auth token from secret for publishing
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} > .npmrc

          # Attempt to publish at the current version - this will skip if the version already exists
          echo "Attempting to publishing latest version"
          ./node_modules/.bin/lerna publish from-package --no-private --dist-tag latest --ignore-scripts --ignore-changes --no-push --yes
